INSERT INTO supplements (name, description, manufacturer, cost, quantity, type, images, created_at, updated_at, deleted_at) VALUES
('SLIN', 'SLIN is a revolutionary insulin mimetic that transports the carbohydrates you eat into your muscles rather than storing them as fat! But to really understand how SLIN works, you must first understand insulin as a hormone, which we continue to fully grasp and utilize.', 'Enhanced', 49.99, 10, 'intake', '{"src": "https://enhancedlabs.com/cdn/shop/files/REF1_1.png?height=2048&v=1687928113&width=2048"}', NOW(), NOW(), NULL),
('Women Daily Multi Vitamins', 'Iron Supplements Multivitamins for Women | 90 Whole Food Blood Builder Iron Pills Tablets with Vitamin C Vitamin B12 Folate Rice Beets Root | Fatigue Anemia Hair Loss Iron & Ferritin Deficiency', 'MegaFood', 60.74, 90, 'intake', '{"src": "https://www.yeswellness.com/cdn/shop/files/women_over_40_one_daily_30tablets__17248.1577202813.1280.1280_3d7204f0-0ef7-4c87-8010-ffbb21b647cc.png?v=1699548023&width=480"}', NOW(), NOW(), NULL),
('Essential Vegan Multivitamin', 'Essential Vegan Multivitamin for Plant-Based Diets - 90 Veg Tablets with B12, D3, Calcium, Iron, Zinc & More. VEGANLY Vitamins Canada', 'VEGANLY Vitamins', 53.99, 90, 'intake', '{"src": "https://m.media-amazon.com/images/I/61mYKPeNbxL._AC_SL1500_.jpg"}', NOW(), NOW(), NULL),
('Men’s Multi', 'Men’s Multi – Daily Multivitamins For Men - 60 Vegan', 'NuBest', 60.99, 60, 'intake', '{"src": "https://www.nubest.com/cdn/shop/files/mensmulti-avatar.png?v=1700881339"}', NOW(), NOW(), NULL),
('NATURELO One Daily Multivitamin for Women', 'NATURELO One Daily Multivitamin for Women - Energy Support - Whole Food Supplement to Nourish Hair, Skin, Nails - Non-GMO - No Soy - Gluten Free - 120 Capsules | 4 Month Supply', 'NATURELO', 46.95, 120, 'intake', '{"src": "https://m.media-amazon.com/images/I/71XN3Lm6-CL._AC_SL1500_.jpg"}', NOW(), NOW(), NULL),
('womens multi', 'Womens Multi (18+) – Vitality & Beauty Formula, Boosts Energy, Immunity & Overall Health With Essential Vitamins, Minerals, Antioxidants, Fruit & Herbal Blends - 60 Vegan Capsules', 'NuBest', 45.55, 60, 'intake', '{"src": "https://www.nubest.com/cdn/shop/files/womensmulti-avatar.png?v=1700881139&width=1946"}', NOW(), NOW(), NULL),
('NUTRAMIN', 'NUTRACELLE NUTRAMIN Daily Vegan Keto Multivitamin Gummies Vitamin C, D2, and Zinc for Immunity, Plant-Based, Sugar-Free, Nut-Free, Gluten-Free, Vitamin A, B, B6, B12 & More 90 Count, 45 Day Supply', 'Nutracelle', 23.39, 90, 'intake', '{"src": "https://th.bing.com/th/id/OIP.2wTXAEcwG7-KY33kMjedXAAAAA?rs=1&pid=ImgDetMain"}', NOW(), NOW(), NULL),
('Creatine Monohydrate', 'Creatine Monohydrate 1000 mg Capsules by Nutritionn - 3-5 g Serving, 150 Capsules - Increases Lean Muscle Mass - Premium Bodybuilding and Sports Supplement', 'Nutritionn', 24.99, 150, 'intake', '{"src": "https://m.media-amazon.com/images/I/61wYwNV6-YL._AC_SL1500_.jpg"}', NOW(), NOW(), NULL),
('Essentials', 'Essentials is packed with natural antioxidants from organic whole foods, to help you look and feel better from the inside out. All ingredients are harvested at the peak of nutrition, and cold-processed to capture all of earth’s bounty.', 'touchstone', 81.00, 90, 'restock', '{"src": "https://assets.thegoodinside.com/shop/uploads/e974c051a3d8f396d7ecae0bea4260e2.jpg?_gl=1*1g4atc1*_gcl_aw*R0NMLjE3MDI5ODI5MzcuQ2owS0NRaUFtNFdzQmhDaUFSSXNBRUpJRXpWcG81MXNfTHJHQkdZT2ZKSGxjYW14NFlzX25BS1JOOHRSdXpQckpFTXdnZlJVT1lKQi1Zd2FBc2p1RUFMd193Y0I.*_gcl_au*MjIwMzI5MDM4LjE3MDI5ODI5Mzc.*FPAU*MjA5NDI5MjE0OC4xNzAyOTgyOTI2"}', NOW(), NOW(), NULL),
('probiotic', 'Crafted with natural ingredients, Cymbiotikas Probiotic restores and maintains healthy gut function. This proprietary formula includes 19 probiotic strains, plant-based prebiotics, and a unique blend of herbal alchemy and amino acids. Our formula helps balance your gut microbiome, boost energy levels, lower stress and reduce digestive issues.', 'YMbiotika', 104.40, 90, 'intake', '{"src": "https://cymbiotika.ca/cdn/shop/files/SproutPDP__Zinccopy_1_2560x.png?v=1688661378"}', NOW(), NOW(), NULL);
